char* externalCharacterNames[] = {
  "Captain Falcon",
  "Donkey Kong",
  "Fox",
  "Mr. Game & Watch",
  "Kirby",
  "Bowser",
  "Link",
  "Luigi",
  "Mario",
  "Marth",
  "Mewtwo",
  "Ness",
  "Peach",
  "Pikachu",
  "Ice Climbers",
  "Jigglypuff",
  "Samus",
  "Yoshi",
  "Zelda",
  "Sheik",
  "Falco",
  "Young Link",
  "Dr. Mario",
  "Roy",
  "Pichu",
  "Ganondorf",
  "Master Hand",
  "Wireframe Male (Boy)",
  "Wireframe Female (Girl)",
  "Giga Bowser",
  "Crazy Hand",
  "Sandbag",
  "Popo",
  "User Select(Event) / None"
};
